package com.zvil.shefing;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main application generated by Netbeans
 * @author Zvi (zvil@zvil.com)
 */
@SpringBootApplication
public class ShefingTestApplication {

	public static void main(String[] args) {
		SpringApplication.run(ShefingTestApplication.class, args);
	}

}
